# USAGE: python sera/main.py --config-name specialization_starlette stage=pipeline name=test

defaults:
  - sera
  - _self_

name: specialize_starlette

generate:
  fns_per_repo: 5000
  insts_per_fn: 1
  existing_repos:
    - org_name: encode
      last_name: starlette
      source: swesmith

distill:
  model:
    name: openai/GLM-4.5-Air
    url: null # <--- FILL IN
  sweagent_wrapper_config:
    num_workers: 24
  args:
    pipeline_repo: starlette

postprocess:
  tool_call_format: hermes
  add_think: false # Set to true if using anthropic
  add_train_key: true
  enforce_submit: true

eval:
  compare_patch_threshold: 0.5
